#Prasad Jawale RL Experiment 1 - Q Learning

**Enviroment 4x4**

S - start state
X - obstacle
R - reward
G - goal state

S . . R

. X X .

. . X .

R . . G

In [ ]:
import numpy as np

grid_size = 4
start_state = (0, 0)
goal_state = (grid_size - 1, grid_size - 1)
obstacles = [(1, 1),(1,2),(2, 2)]
reward_state = [(0, 3), (3, 0)]

actions = ['up', 'down', 'left', 'right']
num_actions = len(actions)

learning_rate = 0.2
discount_factor = 0.8
epsilon = 0.2
num_episodes = 1500

Q_values = np.zeros((grid_size, grid_size, num_actions))

def get_next_state(state, action):
    x, y = state
    if action == 'up':
        return max(x - 1, 0), y
    elif action == 'down':
        return min(x + 1, grid_size - 1), y
    elif action == 'left':
        return x, max(y - 1, 0)
    elif action == 'right':
        return x, min(y + 1, grid_size - 1)

def environment(state, action):
    if state in reward_state:
        return 10
    if state == goal_state:
        return 0
    next_state = get_next_state(state, action)
    if next_state in obstacles:
        return -5
    elif next_state == goal_state:
        return 100
    else:
        return -1

def select_action(state):
    if np.random.rand() < epsilon:
        return np.random.choice(actions)
    else:
        return actions[np.argmax(Q_values[state])]

def update_Q_value(state, action, reward, next_state):
    max_next_Q_value = np.max(Q_values[next_state])
    Q_values[state][actions.index(action)] += learning_rate * (reward + discount_factor * max_next_Q_value - Q_values[state][actions.index(action)])

for episode in range(num_episodes):
    state = start_state
    while state != goal_state:
        action = select_action(state)
        reward = environment(state, action)
        next_state = get_next_state(state, action)
        update_Q_value(state, action, reward, next_state)
        state = next_state

print("Learned Q-values:")
print(Q_values)

path = []
state = start_state
while state != goal_state:
    action = actions[np.argmax(Q_values[state])]
    path.append((state, action))
    state = get_next_state(state, action)
path.append((goal_state, None))

print("\nShortest Path:")
for step in path:
    print(step)


Learned Q-values:
[[[ 27.03071974  34.51701703  27.03072     35.0384    ]
  [ 35.0384      23.03071735  27.03071993  45.048     ]
  [ 45.04799979  44.75999638  35.03839872  57.56      ]
  [ 68.55999989  73.2         56.04799995  68.55999996]]

 [[ 23.25427666  44.81733464  25.16627379  18.42610145]
  [ 35.03839997  21.25125816  16.70970592  24.5962335 ]
  [ 45.04776902  48.93062588  21.90706886  62.2       ]
  [ 57.56        79.          44.75999905  62.19999997]]

 [[ 29.26118853  57.47069761  36.39218439  29.83220217]
  [ 16.71624053  58.10073926  22.2308224   24.30619061]
  [ 44.7576809   21.11212669  24.42515447  78.99970368]
  [ 62.19999984 100.          58.19237447  78.99999952]]

 [[ 45.78246798  56.16069236  57.79524282  73.18503834]
  [ 31.38567323  41.71509994  51.41940577  78.99649368]
  [ 47.97693954  45.0253403   25.9000577   99.99953232]
  [  0.           0.           0.           0.        ]]]

Shortest Path:
((0, 0), 'right')
((0, 1), 'right')
((0, 2), 'right')
((0, 3),