#Prasad Jawale RL Experiment 2 - SARSA


**Enviroment 4x4**

S - start state
X - obstacle
R - reward
G - goal state

S . . R

. X X .

. . X .

R . . G

In [ ]:

import numpy as np

grid_size = 4
start_state = (0, 0)
goal_state = (grid_size - 1, grid_size - 1)
obstacles = [(1, 1), (2, 2)]
reward_state = [(0, 3), (3, 0)]

actions = ['up', 'down', 'left', 'right']
num_actions = len(actions)

learning_rate = 0.2
discount_factor = 0.8
epsilon = 0.2
num_episodes = 1500

Q_values = np.zeros((grid_size, grid_size, num_actions))

def get_next_state(state, action):
    x, y = state
    if action == 'up':
        return max(x - 1, 0), y
    elif action == 'down':
        return min(x + 1, grid_size - 1), y
    elif action == 'left':
        return x, max(y - 1, 0)
    elif action == 'right':
        return x, min(y + 1, grid_size - 1)

def environment(state, action):
    if state in reward_state:
        return 10
    if state == goal_state:
        return 0
    next_state = get_next_state(state, action)
    if next_state in obstacles:
        return -5
    elif next_state == goal_state:
        return 100
    else:
        return -1

def select_action(state):
    if np.random.rand() < epsilon:
        return np.random.choice(actions)
    else:
        return actions[np.argmax(Q_values[state])]

def update_SARSA_Q_value(state, action, reward, next_state, next_action):
    next_Q_value = Q_values[next_state][actions.index(next_action)]
    Q_values[state][actions.index(action)] += learning_rate * (reward + discount_factor * next_Q_value - Q_values[state][actions.index(action)])

for episode in range(num_episodes):
    state = start_state
    action = select_action(state)
    while state != goal_state:
        reward = environment(state, action)
        next_state = get_next_state(state, action)
        next_action = select_action(next_state)
        update_SARSA_Q_value(state, action, reward, next_state, next_action)
        state = next_state
        action = next_action

print("Learned Q-values:")
print(Q_values)

path = []
state = start_state
while state != goal_state:
    action = actions[np.argmax(Q_values[state])]
    path.append((state, action))
    state = get_next_state(state, action)
path.append((goal_state, None))

print("\nShortest Path:")
for step in path:
    print(step)


Learned Q-values:
[[[ 20.38845003  21.65661421  20.30038603  26.56294584]
  [ 27.72532024  17.21416429  19.39449125  37.27322684]
  [ 36.05650184  36.93403101  26.13973547  51.39591401]
  [ 60.41277835  65.44960147  49.1747793   59.89724252]]

 [[ 16.45352833  31.70753225  21.32858576  14.0197395 ]
  [ 26.16088882   6.79208901  13.80200232  22.98340035]
  [ 34.59058441  22.43230096  15.55647295  54.46134332]
  [ 49.80407082  72.71186488  42.58662295  56.61072811]]

 [[ 13.67713911  50.86526961  30.88551616  17.74499351]
  [  8.57763878  21.46461111  35.10305699   2.08034678]
  [ 26.88620338  38.44872859  14.3528258   78.76819923]
  [ 51.0821461  100.          35.48675768  77.49808879]]

 [[ 42.46162388  51.89679134  52.38884998  66.34950143]
  [ 22.25346933  52.34405717  43.08439893  76.22442896]
  [ 44.15356951  68.4635027   34.56724488 100.        ]
  [  0.           0.           0.           0.        ]]]

Shortest Path:
((0, 0), 'right')
((0, 1), 'right')
((0, 2), 'right')
((0, 3),